version = 1
SPDX-PackageName = "cookbook"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/cookbook"

[[annotations]]
path = ["l10n/*.js", "l10n/*.json"]
SPDX-FileCopyrightText = "2019-2024 Nextcloud translators"
SPDX-License-Identifier = "AGPL-3.0-only OR AGPL-3.0-or-later"

[[annotations]]
path = [".changelog/versions/*.md", ".changelog/current/*.md"]
SPDX-FileCopyrightText = "2019-2026 Nextcloud cookbook contributors"
SPDX-License-Identifier = "AGPL-3.0-only OR AGPL-3.0-or-later"