#!/bin/sh

# set -x

lines_before=`git stash list | wc -l`
git stash push --keep-index -q
lines_after=`git stash list | wc -l`

cleanup() {
	if [ $lines_before -lt $lines_after ]; then
		git stash pop -q
	fi
}

trap cleanup EXIT

if [ -e 'node_modules/.bin/eslint' ]; then
	npm run --silent eslint || { echo 'The javascript code seems to be not satifying the eslint linter.'; exit 1; }
fi
