# SPDX-FileCopyrightText: 2026 Nextcloud cookbook contributors
#
# SPDX-License-Identifier: AGPL-3.0-only OR AGPL-3.0-or-later

theme: jekyll-theme-slate
repository: nextcloud/cookbook
exclude:
    - "Makefile"
    - Makefile.local
    - .gitignore
    - "vendor/"
    - Gemfile
    - Gemfile.lock
# plugins:
#     - jekyll-spaceship
markdown: kramdown
kramdown:
    input: GFM
