# SPDX-FileCopyrightText: 2026 Nextcloud cookbook contributors
#
# SPDX-License-Identifier: AGPL-3.0-only OR AGPL-3.0-or-later

name: Additional tests for pull requests

on:
    pull_request:

jobs:
    
    todo-checker:
        name: Check for added todo messages
        runs-on: ubuntu-24.04
        steps:
            -   name: Git version output
                run: git version
            -   name: Manual checkout of the app (base repo)
                run: |
                    REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                    BRANCH="${GITHUB_REF/#refs\/heads\//}"

                    git clone --filter=tree:0 "$REPO" .
            -   name: Manual checkout of the app (PR head)
                env:
                    URL: ${{ github.event.pull_request.head.repo.html_url }}
                    HEAD_REF: ${{ github.head_ref }}
                run: |
                    git remote add head "$URL"
                    git fetch head --filter=tree:0
                    
                    git checkout -b head-branch head/$HEAD_REF
            -   name: Status of current git workspace
                run: |
                    git branch
                    git status
            -   name: Check for open TODO annotations in source code
                uses: ./.github/actions/check-todo

    appinfo:
        name: Check for matching app info file
        runs-on: ubuntu-24.04

        steps:
            -   name: Checkout of the app
                uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
                with:
                    fetch-depth: 1
                    persist-credentials: false
                
            -   name: Install dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install jq
                    pip install yq
                    echo "$HOME/.local/bin" >> "$GITHUB_PATH"

            -   name: Perform the test
                env:
                    MAIN_FILE: appinfo/info.xml
                    DIST_FILE: .github/actions/deploy/appinfo/info.xml.dist
                run: |
                    echo "Normalize the actual appinfo file"    
                    xq -x 'del(.info.version)' "$MAIN_FILE" > /tmp/main-info.xml
                    xq -x 'del(.info.version)' "$DIST_FILE" > /tmp/dist-info.xml

                    echo '::group::Debug output'
                    tail -n 100 /tmp/main-info.xml /tmp/dist-info.xml
                    echo '::endgroup::'

                    if ! diff -q /tmp/main-info.xml /tmp/dist-info.xml > /dev/null; then
                    echo '::error::The app info file differs from the dist file. Please check manually!'
                    exit 1
                    fi

            -   name: Download schema
                run: wget https://raw.githubusercontent.com/nextcloud/appstore/master/nextcloudappstore/api/v1/release/info.xsd

            -   name: Lint info.xml
                uses: ChristophWurst/xmllint-action@7c54ff113fc0f6d4588a15cb4dfe31b6ecca5212
                with:
                    xml-file: ./appinfo/info.xml
                    xml-schema-file: ./info.xsd
    
    package-lint:
        name: Make sure the package.json is well-formatted
        runs-on: ubuntu-24.04

        steps:
            -   name: Checkout of the app
                uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
                with:
                    fetch-depth: 1
                    persist-credentials: false
            -   name: Read package.json node and npm engines version
                uses: skjnldsv/read-package-engines-version-actions@06d6db44aa62f4609ba070f556ec24bc99fb85cb # v4
                id: versions
                # Continue if no package.json
                continue-on-error: true
                with:
                    path: .
                    fallbackNode: '^24'
                    fallbackNpm: '^11.3'
            -   name: Set up node ${{ steps.versions.outputs.nodeVersion }}
                # Skip if no package.json
                if: ${{ steps.versions.outputs.nodeVersion }}
                uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
                with:
                    node-version: ${{ steps.versions.outputs.nodeVersion }}
            -   name: Set up npm ${{ steps.versions.outputs.npmVersion }}
                # Skip if no package.json
                if: ${{ steps.versions.outputs.npmVersion }}
                run: npm i -g 'npm@${{ steps.versions.outputs.npmVersion }}'
            -   name: Get the date
                id: date
                run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
            -   name: Cache NPM cache
                uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
                with:
                    path: |
                        ~/.npm
                        node_modules
                    key: ${{ runner.os }}-node-${{ steps.date.outputs.date }}-${{ hashFiles('package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-${{ steps.date.outputs.date }}-
                        ${{ runner.os }}-node-

            -   name: Install NPM modules
                run: npm ci

            -   name: Perform the test
                run: |
                    npm run package-lint

                    if [ $(git diff --name-only package.json | wc -l) -gt 0 ]; then
                    echo '::error file=package.json::The package.json file is not validly formatted.'
                    echo '::notice::It is suggested to run `npm run package-lint` and commit locally.'
                    exit 1
                    fi

    fixup-check:
        name: Block fixup and squash commits
        runs-on: ubuntu-latest

        steps:
            -   name: Run check
                uses: xt0rted/block-autosquash-commits-action@79880c36b4811fe549cfffe20233df88876024e7
                with:
                    repo-token: ${{ secrets.GITHUB_TOKEN }}
